name: ALKiln Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  alkiln-tests:
    runs-on: ubuntu-latest
    name: Run ALKiln tests
    env:
      REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run ALKiln tests
        uses: SuffolkLITLab/ALKiln@v5
        with:
          SERVER_URL: ${{ secrets.SERVER_URL }}
          DOCASSEMBLE_DEVELOPER_API_KEY: ${{ secrets.DOCASSEMBLE_DEVELOPER_API_KEY }}